[package]
name = "rivctrl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-monitor = "0.1.1"
serde = "1"
serde_derive = "1"
serialport = "3.3"
sysinfo = "0.20.3"
toml = "0.5"